/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.seleniumhq.selenium.selenium.java)
    api(libs.org.seleniumhq.selenium.selenium.server)
    testImplementation(libs.junit.junit)
}

group = "sit707_week5"
version = "1.0-SNAPSHOT"
description = "task5_3H"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
